= SailPoint improved
:toc:
:toclevels: 5

== Description
Current project contains modules to improve SailPoint IdentityIQ projects. The main aims of the projects: simplify some areas in IdentityIQ, increasing performance, doing IdentityIQ developers life easier.

== Structure

Modules:

. *sail-point-annotation-parent* - group of modules contains annotations and processors for generating xml sources from java classes
.. *sail-point-annotation* - all external annotations, as for generating xml and as for other modules
.. *sail-point-annotation-processor* - annotation processors for generating xml from java classes. Current implementation supported generating:
* [*] Rules
* [*] Custom objects

.. *sail-point-improved* - extends standard IdentityIQ classes for improvements (e.g. JavaRuleRunner)
.. *sail-point-customization* - shows how to use all this stuff.

== Build
For start using it:

. Add 2 IdentityIQ dependencies to local maven repository. Script for adding jars is located in _/bin_ directory. List of custom jars:
.. *identityiq.jar*
.. *connector-bundle.jar*

IMPORTANT: All versions in main pom for dependencies were taken from lib directory of identityiq,war. They all quite old and one (lucene) with vulnerable.

Build command:
----
mnv clean install
----

== Improvements
All current improvements for IdentityIQ are in this block.

=== Rule

All rules can be separated into 2 groups: with output and none.

[plantuml]
....
interface JavaRuleExecutor
JavaRuleExecutor : +Object execute(JavaRuleContext)

class AbstractJavaRuleExecutor
class AbstractNoneOutputJavaRuleExecutor

JavaRuleExecutor <|-- AbstractJavaRuleExecutor
AbstractJavaRuleExecutor <|-- AbstractNoneOutputJavaRuleExecutor
....

==== Example
Simple JDBCBuildMap rule type implementation. According to documentation JDBCBuildMap has input attributes and output: map of names/values.

Name of new rule: SimpleJDBCBuildMapRule. Functionality: check value from column: active_status and if value is 'T', than put true, else false (very simple rule). Code:
[source,java]
----
/**
 * Simple implementation of {@link JDBCBuildMapRule} rule
 */
@Slf4j
@Rule(value = "Simple JDBC build map rule", type = sailpoint.object.Rule.Type.JDBCBuildMap)
public class SimpleJDBCBuildMapRule extends JDBCBuildMapRule {

    /**
     * Active status attribute name
     */
    static final String ATTR_ACTIVE_STATUS_NAME = "active_status";

    /**
     * Active status true value
     */
    static final String TRUE_ACTIVE_STATUS_VALUE = "T";

    /**
     * Check default string attribute {@link SimpleJDBCBuildMapRule#ATTR_ACTIVE_STATUS_NAME} and replace it with boolean value:
     * Y - true
     * all other values - false
     */
    @Override
    @Argument(name = "map", type = ArgumentType.RETURNS, isReturnsType = true)
    protected Map<String, Object> internalExecute(JavaRuleContext context,
                                                  JDBCBuildMapRuleArguments arguments) throws GeneralException {
        try {
            log.debug("Try to get default map");
            Map<String, Object> map = JDBCConnector.buildMapFromResultSet(arguments.getResult());

            log.debug("Check:[{}] attribute in default map", ATTR_ACTIVE_STATUS_NAME);
            log.trace("Default map:[{}]", map);
            String activeStatus = (String) map.get(ATTR_ACTIVE_STATUS_NAME);
            log.trace("[{}] attribute value in default map:[{}]", ATTR_ACTIVE_STATUS_NAME, activeStatus);
            map.put(ATTR_ACTIVE_STATUS_NAME, TRUE_ACTIVE_STATUS_VALUE.equalsIgnoreCase(activeStatus));
            return map;
        } catch (Exception ex) {
            log.error("Got error:[{}] while executing rule", ex.getMessage(), ex);
            throw new GeneralException(ex);
        }
    }
}

----
Result generated XML:
[source,xml]
----
<?xml version='1.0' encoding='UTF-8'?>

<!DOCTYPE Rule PUBLIC "sailpoint.dtd" "sailpoint.dtd">

<Rule language="java" name="Simple JDBC build map rule" type="JDBCBuildMap">
  <Description>Simple implementation of {@link JDBCBuildMapRule} rule</Description>
    <Signature returnType="java.util.Map">
      <Inputs>
        <Argument name="application" type="sailpoint.object.Application">
          <Description>A reference to the Application object</Description>
        </Argument>
        <Argument name="schema" type="sailpoint.object.Schema">
          <Description>A reference to the Schema object for the JDBC source being read</Description>
        </Argument>
        <Argument name="state" type="java.util.Map">
          <Description>A Map that can be used to store and share data between executions of this rule during a single aggregation run</Description>
        </Argument>
        <Argument name="result" type="java.sql.ResultSet">
          <Description>The current ResultSet from the JDBC connector</Description>
        </Argument>
        <Argument name="connection" type="java.sql.Connection">
          <Description>A reference to the current SQL connection</Description>
        </Argument>
      </Inputs>
      <Returns>
        <Argument name="map" type="java.util.Map">
          <Description>Check default string attribute {@link SimpleJDBCBuildMapRule#ATTR_ACTIVE_STATUS_NAME} and replace it with boolean value:
            Y - true
            all other values - false</Description>
        </Argument>
      </Returns>
    </Signature>
  <Source>com.sailpoint.rule.connector.SimpleJDBCBuildMapRule</Source>
</Rule>
----
Advantages of using java classes as source of rules:

. No need to write code in xml
. Debugging rules (no beanshell)
. Performance improvements (~10 times faster than beanshell)
. Tests (mockito, jmockit...)
. No need to copy-paste from java class code to xml and vice versa

=== Custom object

== Dockerization
Sources: */bin/docker* +
Documentation: link:bin/docker/README.adoc[README.adoc]